
// Enhanced constants based on training data and Python implementation
export const BUSINESS_SUFFIXES = new Set([
  'INC', 'LLC', 'LTD', 'PLC', 'PTY', 'CORP', 'CO', 'COMPANY', 'LLP', 'LP', 'PC',
  'PLLC', 'BANK', 'TRUST', 'FOUNDATION', 'SOCIETY', 'ASSOCIATION', 'ASSN',
  'UNIVERSITY', 'HOSPITAL', 'INSTITUTE', 'CHURCH', 'GMBH', 'SARL', 'SA',
  'CORPORATION', 'INCORPORATED', 'LIMITED', 'GROUP', 'ASSOCIATES', 'PARTNERS',
  'ENTERPRISES', 'HOLDINGS', 'PROPERTIES', 'SERVICES', 'SOLUTIONS', 'SYSTEMS',
  'TECHNOLOGIES', 'COMMUNICATIONS', 'DEPARTMENT', 'AUTHORITY', 'DISTRICT',
  'AGENCY', 'DIVISION', 'INTERNATIONAL', 'GLOBAL'
]);

export const BUSINESS_KEYWORDS = new Set([
  'AUTO', 'PLUMBING', 'TRAVEL', 'CONSULTING', 'SERVICES', 'GROUP', 'HOLDINGS',
  'PROPERTY', 'PROPERTIES', 'PARTNERS', 'ENTERPRISE', 'ENTERPRISES', 'MEDIA',
  'SOLUTIONS', 'TECHNOLOGIES', 'LOGISTICS', 'CONSTRUCTION', 'CONTRACTING',
  'BUILDING', 'MANUFACTURING', 'SUPPLY', 'EQUIPMENT', 'TOOLS', 'HARDWARE',
  'MATERIALS', 'WHOLESALE', 'RETAIL', 'RESTAURANT', 'CAFE', 'CATERING',
  'FOOD', 'BAKERY', 'DELI', 'BAR', 'GRILL', 'PIZZA', 'BURGER', 'COFFEE',
  'HOTEL', 'MOTEL', 'INN', 'MEDICAL', 'DENTAL', 'HEALTH', 'CLINIC',
  'PHARMACY', 'THERAPY', 'WELLNESS', 'FITNESS', 'GYM', 'SPA', 'MASSAGE',
  'TECH', 'SOFTWARE', 'COMPUTER', 'IT', 'INTERNET', 'WEB', 'DIGITAL',
  'PHONE', 'MOBILE', 'WIRELESS', 'CABLE', 'SATELLITE', 'TRANSPORT',
  'SHIPPING', 'DELIVERY', 'MOVING', 'STORAGE', 'WAREHOUSE', 'TRUCK',
  'TAXI', 'CAB', 'RENTAL', 'LEASE', 'PROFESSIONAL', 'QUALITY', 'PREMIUM',
  'ELITE', 'EXPERT', 'MASTER', 'ADVANCED', 'SUPERIOR', 'BEST', 'TOP',
  'FIRST', 'PRIME', 'CHOICE', 'QUICK', 'FAST', 'RAPID', 'INSTANT',
  'SAME', 'DAY', 'LOCKSMITH', 'EXPRESS', 'REPAIR', 'MAINTENANCE',
  'INSTALLATION', 'ELECTRICAL', 'ROOFING', 'FLOORING', 'PAINTING',
  'CLEANING', 'LANDSCAPING', 'PEST', 'CONTROL', 'SECURITY', 'ALARM',
  'FIRE', 'PROTECTION', 'EMERGENCY', 'HVAC', 'AIR', 'CONDITIONING',
  'HEATING', 'POOLS', 'MECHANICAL', 'EVENTS', 'PLANNERS', 'CITY',
  'COUNTY', 'STATE', 'DEPARTMENT', 'AUTHORITY', 'DISTRICT', 'GOVERNMENT',
  'MUNICIPAL', 'FEDERAL', 'BUREAU', 'COMMISSION', 'BOARD', 'OFFICE',
  'ADMINISTRATION', 'COURT', 'PUBLIC', 'SCHOOL', 'APARTMENT', 'APARTMENTS',
  'ELEVATOR', 'GLASS', 'MIRROR', 'CARPET', 'SPRINKLER', 'COPIER',
  'COMMUNICATIONS', 'NETWORK', 'TELECOM', 'VILLAGE', 'VILLA', 'VILLAS',
  'RIDGE', 'PARK', 'PLACE', 'PLAZA', 'TOWER', 'TOWERS', 'CROSSING',
  'CROSSINGS', 'STATION', 'POINT', 'GROVE', 'GLEN', 'SPRINGS', 'HEIGHTS',
  'HILLS', 'GARDENS', 'COURT', 'CLUB', 'RESERVE', 'LANDING', 'COMMONS',
  'MEADOWS', 'OAKS', 'VIEW', 'VISTA', 'EDGE', 'WOODS', 'CREEK'
]);

export const HONORIFICS = new Set([
  'MR', 'MS', 'MRS', 'DR', 'PROF', 'REV', 'SIR', 'HON', 'MISS', 'MD',
  'JD', 'CPA', 'ESQ', 'PHD', 'DDS', 'DVM', 'RN', 'DO', 'DC', 'LPN',
  'PA', 'NP', 'LCSW', 'CRNA', 'PTA', 'OT', 'PT', 'CAPT', 'CPT', 'COL',
  'GEN', 'MAJ', 'LT', 'SGT', 'ADM', 'CMDR', 'FR', 'PASTOR', 'RABBI',
  'IMAM', 'BISHOP', 'ELDER', 'DEACON', 'DAME', 'LORD', 'LADY', 'HRH',
  'SHEIKH', 'EMINENCE'
]);

export const GENERATION_SUFFIXES = new Set([
  'JR', 'SR', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X',
  '2ND', '3RD', '4TH', '5TH', '6TH', '7TH', '8TH', '9TH', '10TH'
]);

// Comprehensive first names database (subset - in production would be much larger)
export const GIVEN_NAMES = new Set([
  'JAMES', 'JOHN', 'ROBERT', 'MICHAEL', 'WILLIAM', 'DAVID', 'RICHARD', 'CHARLES',
  'JOSEPH', 'THOMAS', 'CHRISTOPHER', 'DANIEL', 'PAUL', 'MARK', 'DONALD', 'GEORGE',
  'KENNETH', 'STEVEN', 'EDWARD', 'BRIAN', 'RONALD', 'ANTHONY', 'KEVIN', 'JASON',
  'MATTHEW', 'GARY', 'TIMOTHY', 'JOSE', 'LARRY', 'JEFFREY', 'FRANK', 'SCOTT',
  'ERIC', 'STEPHEN', 'ANDREW', 'RAYMOND', 'GREGORY', 'JOSHUA', 'JERRY', 'DENNIS',
  'WALTER', 'PATRICK', 'PETER', 'HAROLD', 'DOUGLAS', 'HENRY', 'CARL', 'ARTHUR',
  'RYAN', 'ROGER', 'JOE', 'JUAN', 'JACK', 'ALBERT', 'JONATHAN', 'JUSTIN',
  'TERRY', 'AUSTIN', 'SEAN', 'BENNIE', 'MARY', 'PATRICIA', 'JENNIFER', 'LINDA',
  'ELIZABETH', 'BARBARA', 'SUSAN', 'MARGARET', 'DOROTHY', 'LISA', 'NANCY',
  'KAREN', 'BETTY', 'HELEN', 'SANDRA', 'DONNA', 'CAROL', 'RUTH', 'SHARON',
  'MICHELLE', 'LAURA', 'SARAH', 'KIMBERLY', 'DEBORAH', 'AMY', 'ANGELA', 'ASHLEY',
  'BRENDA', 'EMMA', 'OLIVIA', 'CYNTHIA', 'MARIE', 'JANET', 'CATHERINE', 'FRANCES',
  'CHRISTINE', 'SAMANTHA', 'DEBRA', 'RACHEL', 'CAROLYN', 'VIRGINIA', 'MARIA',
  'HEATHER', 'DIANE', 'JULIE', 'JOYCE', 'VICTORIA', 'KELLY', 'CHRISTINA', 'JOAN',
  'EVELYN', 'LAUREN', 'JUDITH', 'MEGAN', 'CHERYL', 'ANDREA', 'HANNAH', 'JACQUELINE',
  'MARTHA', 'GLORIA', 'SARA', 'JANICE', 'ANN', 'KATHRYN', 'ABIGAIL', 'SOPHIA',
  'JEAN', 'ALICE', 'JUDY', 'ISABELLA', 'JULIA', 'GRACE', 'AMBER', 'DENISE',
  'DANIELLE', 'MARILYN', 'BEVERLY', 'CHARLOTTE', 'DIANA', 'KRISTEN', 'TYLER',
  'JESSICA', 'ASHLEY', 'ERIK', 'CHRISTINE', 'CARLY', 'VICTORIA', 'ANTONIO',
  'NIKKI', 'NATASHA', 'GUSTAVO', 'VANESSA', 'XAVIER', 'ALIYAH', 'ALDO', 'MARIO',
  'CARLOS', 'LAUREN', 'NAOMI', 'MARITZA', 'ADAM', 'KAYLA', 'WESTLEY', 'FRANCO',
  'KARA', 'BLAIR', 'TARYN', 'NATALIA', 'PEDRO', 'CYNTHIA', 'MARSHALL', 'JINNY',
  'MAYRA', 'YELITZA', 'GLEN', 'KELLY', 'LINDSEY', 'SERGIO', 'STEPHANY', 'ALEXIS',
  'LILIA', 'STANLEY', 'DENISSE', 'EMILY', 'RACHEL', 'SAMANTHA', 'WALTER',
  'GUADALUPE', 'KEITH', 'MEILIN', 'CLAUDIA', 'KATHERINE', 'KORI', 'CURTIS',
  'FELICIA', 'LISSA', 'LORENA', 'IRA', 'KATHY', 'PATRICK', 'LARISSA', 'KRISTIR',
  'JORY', 'JUSTIN', 'BRIANA', 'COLLEEN', 'ROY', 'ARIANA', 'MANN', 'NADINE'
]);
