
// SIGNIFICANTLY EXPANDED first names database based on training data patterns
export const COMMON_FIRST_NAMES = new Set([
  // Core English first names from training data
  'JOSE', 'JUAN', 'JESUS', 'MIGUEL', 'CARLOS', 'LUIS', 'FRANCISCO', 'JORGE', 'ANTONIO', 'MANUEL',
  'MARIO', 'PEDRO', 'DAVID', 'MICHAEL', 'JAMES', 'JOHN', 'ROBERT', 'WILLIAM', 'RICHARD', 'JOSEPH',
  'THOMAS', 'CHARLES', 'CHRISTOPHER', 'DANIEL', 'MATTHEW', 'ANTHONY', 'MARK', 'DONALD', 'STEVEN',
  'PAUL', 'ANDREW', 'JOSHUA', 'KENNETH', 'KEVIN', 'BRIAN', 'GEORGE', 'TIMOTHY', 'RONALD', 'JASON',
  'EDWARD', 'JEFFREY', 'RYAN', 'JACOB', 'GARY', 'NICHOLAS', 'ERIC', 'JONATHAN', 'STEPHEN', 'LARRY',
  'JUSTIN', 'SCOTT', 'BRANDON', 'BENJAMIN', 'SAMUEL', 'GREGORY', 'ALEXANDER', 'PATRICK', 'FRANK',
  'RAYMOND', 'JACK', 'DENNIS', 'JERRY', 'TYLER', 'AARON', 'HENRY', 'DOUGLAS', 'PETER', 'NATHAN',
  
  // Female names from training data
  'MARIA', 'ANA', 'CARMEN', 'ROSA', 'ISABEL', 'TERESA', 'GLORIA', 'PATRICIA', 'LINDA', 'BARBARA',
  'ELIZABETH', 'JENNIFER', 'SUSAN', 'MARGARET', 'DOROTHY', 'LISA', 'NANCY', 'KAREN', 'BETTY',
  'HELEN', 'SANDRA', 'DONNA', 'CAROL', 'RUTH', 'SHARON', 'MICHELLE', 'LAURA', 'SARAH', 'KIMBERLY',
  'DEBORAH', 'JESSICA', 'SHIRLEY', 'CYNTHIA', 'ANGELA', 'MELISSA', 'BRENDA', 'AMY', 'ANNA',
  'REBECCA', 'VIRGINIA', 'KATHLEEN', 'PAMELA', 'MARTHA', 'DEBRA', 'AMANDA', 'STEPHANIE', 'CAROLYN',
  'CHRISTINE', 'MARIE', 'JANET', 'CATHERINE', 'FRANCES', 'ANN', 'JOYCE', 'DIANE', 'ALICE', 'JULIE',
  'HEATHER', 'TERESA', 'DORIS', 'GLORIA', 'EVELYN', 'JEAN', 'CHERYL', 'MILDRED', 'KATHERINE',
  'JOAN', 'ASHLEY', 'JUDITH', 'ROSE', 'JANICE', 'KELLY', 'NICOLE', 'JUDY', 'CHRISTINA', 'KATHY',
  'THERESA', 'BEVERLY', 'DENISE', 'TAMMY', 'IRENE', 'JANE', 'LORI', 'RACHEL', 'MARILYN', 'ANDREA',
  'KATHRYN', 'LOUISE', 'SARA', 'ANNE', 'JACQUELINE', 'WANDA', 'BONNIE', 'JULIA', 'RUBY', 'LOIS',
  'TINA', 'PHYLLIS', 'NORMA', 'PAULA', 'DIANA', 'ANNIE', 'LILLIAN', 'EMILY', 'ROBIN', 'PEGGY',
  
  // Hispanic names from training data
  'ALEJANDRO', 'FERNANDO', 'RICARDO', 'ALBERTO', 'EDUARDO', 'ROBERTO', 'OSCAR', 'SALVADOR',
  'RAFAEL', 'ARMANDO', 'RUBEN', 'SERGIO', 'ENRIQUE', 'MARCO', 'VICTOR', 'ARTURO', 'RAUL',
  'RAMIRO', 'ISMAEL', 'EDGAR', 'DANIEL', 'GERARDO', 'ALFREDO', 'FELIPE', 'EMILIO', 'RODOLFO',
  'IGNACIO', 'CESAR', 'MARTIN', 'GUSTAVO', 'ADRIAN', 'HECTOR', 'GUILLERMO', 'JOAQUIN', 'GILBERTO',
  'CRISTINA', 'VERONICA', 'ADRIANA', 'BEATRIZ', 'DOLORES', 'ESPERANZA', 'GUADALUPE', 'JOSEFA',
  'LUCIA', 'MARCELA', 'MARGARITA', 'MONICA', 'OLGA', 'PILAR', 'SILVIA', 'SONIA', 'SUSANA',
  'YOLANDA', 'ELENA', 'GRACIELA', 'LETICIA', 'LIDIA', 'LOURDES', 'MARIBEL', 'MIRIAM', 'NORMA',
  'PATRICIA', 'SOLEDAD', 'VIRGINIA', 'XIMENA', 'CLAUDIA', 'FABIOLA', 'GABRIELA', 'ANDREA',
  
  // Common nicknames and short forms
  'ALEX', 'ANDY', 'TONY', 'MIKE', 'JIM', 'BOB', 'BILL', 'STEVE', 'DAVE', 'CHRIS', 'MATT',
  'RICK', 'TOM', 'NICK', 'JACK', 'JEFF', 'GREG', 'MARK', 'SCOTT', 'BRAD', 'CHAD', 'CRAIG',
  'DREW', 'EVAN', 'KYLE', 'LUKE', 'NOAH', 'OWEN', 'SETH', 'TODD', 'WADE', 'ZACH',
  'SUE', 'JANE', 'JEAN', 'JOAN', 'LYNN', 'ANNE', 'KATE', 'ROSE', 'RUTH', 'BETH', 'DAWN',
  'HOPE', 'JOY', 'KIM', 'LEE', 'MAY', 'PAM', 'RAE', 'TARA', 'VERA', 'ZOE'
]);
