
// Comprehensive exclusion keywords based on your provided list
const COMPREHENSIVE_EXCLUSION_KEYWORDS = [
  'ACCOUNTING OFFICE',
  'ACCOUNTS PAYABLE',
  'ADJUDICATION',
  'ADMINISTRATION',
  'ADP',
  'ADVANTA',
  'AEP',
  'AETNA',
  'aflac',
  'AGENCY',
  'AGRICULTURAL',
  'AIG',
  'alabama power',
  'alagasco',
  'ALLY',
  'ALPHERA FINANCIAL',
  'ALTRIA',
  'AMERICAN ELECTRIC',
  'AMERICAN EXPRESS',
  'AMERICAN FAMILY',
  'AMERIPRISE',
  'ameris bank',
  'AMERISURE',
  'AMEX',
  'AMICA',
  'ANNUITY',
  'ANTHEM',
  'ARBITRATION',
  'archer energy',
  'ARCHIVES',
  'ARIZONA PUBLIC SERVICE',
  'ARMY',
  'ARVEST BANK',
  'ASSET MANAGEMENT',
  'ASSURANCE',
  'ASYLUM',
  'AT & T',
  'AT&T',
  'ATT',
  'AUDIT',
  'AURORA ENERGY',
  'AUSTIN ENERGY',
  'AUTHORITY',
  'AVISTA',
  'AXA',
  'BANC',
  'BANC CORP',
  'BANCORP',
  'BANK',
  'Bank of',
  'BANK OF AMERICA',
  'BANKCORP',
  'BARCLAYS',
  'BAYLOR SCOTT & WHITE',
  'BENEFITS',
  'BEREAVEMENT',
  'BLUE CARE',
  'BLUE CROSS',
  'BLUE SHIELD',
  'BOARD',
  'BOARD OF EDUCATION',
  'board of trustees',
  'BOND',
  'BORDER',
  'BOROUGH',
  'BROKER',
  'BROKERAGE',
  'BUREAU',
  'BUSINESS TRUST',
  "CABELA'S CLUB VISA",
  'CALIFORNIA DEPARTMENT',
  'CALPERS',
  'CAPITAL',
  'CAPITAL GROUP',
  'CAPITAL ONE',
  'CAPITOL',
  'CAPTIVE FINANCE',
  'CARMAX AUTO FINANCE',
  'CAROLINA POWER',
  'CATERPILLAR FINANCIAL',
  'CBIZ PAYROLL',
  'CELTIC BANK',
  'census bureau',
  'CENTENE',
  'CENTRAL BANK',
  'CENTRAL HUDSON',
  'CENTURYLINK',
  'CERIDIAN',
  'CERRO GORDO COUNTY',
  'chamber of commerce',
  'CHARLES SCHWAB',
  'CHARLOTTE WATER',
  'CHARTER COMMUNICATIONS',
  'CHASE',
  'CHEVRON CREDIT',
  'child support',
  'CIGNA',
  'CINCINNATI BELL',
  'CIRCUIT COURT',
  'CITI',
  'citi bank',
  'CITIBANK',
  'CITY',
  'CITY LIGHT',
  'CITY OF',
  'city treasurer',
  'CITY UTILITIES',
  'CIVIC CENTER',
  'CLARKE ENERGY',
  'CLOUD COUNTY',
  'COBANK',
  'COCA‑COLA CREDIT UNION',
  'COLLEGE',
  'colonial life',
  'COMCAST',
  'commercial card',
  'commerence bank',
  'COMMISSION',
  'COMMITTEE',
  'COMMONWEALTH',
  'commonwealth of',
  'COMMUNITY BANK',
  'COMMUNITY COLLEGE',
  'COMPENSATION',
  'COMPTROLLER',
  'CON EDISON',
  'CONSERVANCY',
  'CONSOLIDATED',
  'CONSORTIUM',
  'Constellation',
  'CONSUMERS ENERGY',
  'CONTROLLER',
  'COOPERATIVE',
  'CORPORATE TRUST',
  'corporate trust clearing',
  'CORPS OF ENGINEERS',
  'CORRECTIONAL',
  'CORRECTIONS',
  'COUNTY',
  'county assessor',
  'county of',
  'county tax collector',
  'county treasurer',
  'COURT',
  'cox',
  'CREDIT',
  'CREDIT ACCEPTANCE',
  'CREDIT CARD',
  'CREDIT CORP',
  'CREDIT ONE',
  'CREDIT UNION',
  'CREDITORS',
  'CROWN CASTLE',
  'CUSTODIAN',
  'CUSTOMS',
  'D&B',
  'DEACONESS',
  'DEBT',
  'DEBT COLLECTION',
  'DECATUR UTILITIES',
  'DEFENSE',
  'DEFERRED COMP',
  'DELAWARE POWER',
  'delta dental',
  'DEPARTMENT',
  'department of labor',
  'department of revenue',
  'department of taxation',
  'DEPOSITORY',
  'dept of revenue',
  'dept of taxation',
  'DES MOINES WATER',
  'disbursement',
  'DIVISION',
  'DOD',
  'DOMINION ENERGY',
  'DOT',
  'DUKE ENERGY',
  'EASTERN BANK',
  'EATON VANCE',
  'ELECTRIC',
  'ELECTRIC CO',
  'ELECTRIC CO‑OP',
  'ELECTRIC COOPERATIVE',
  'ELECTRICAL',
  'ELEMENT FLEET',
  'ELIGIBILITY OFFICE',
  'ELIZABETHTOWN GAS',
  'EMERA',
  'EMPLOYEE',
  'EMPLOYEE BENEFIT',
  'EMPLOYEE BENEFIT BOARD',
  'EMPLOYEE EXPENSE',
  'EMPLOYEES RETIREMENT',
  'ENERGY',
  'ENFORCEMENT',
  'ENTERGY',
  'ENVIRONMENTAL',
  'EQUAL OPPORTUNITY',
  'EQUITY TRUST',
  'ERICSSON CREDIT',
  'ESA PAYROLL',
  'ESCROW',
  'EVERSOURCE',
  'EXCELLUS',
  'EXCISE',
  'EXPENSE REIMBURSEMENT',
  'EXPRESS SCRIPTS',
  'F&B',
  'family trust',
  'FANNIE MAE',
  'FARM BUREAU',
  'FARM CREDIT',
  'farmers and merchants bank',
  'FARMERS INSURANCE',
  'FBI',
  'FDIC',
  'FEDERAL',
  'FEDERAL EXPRESS FREIGHT',
  'FEDERAL RESERVE',
  'FEDEX FREIGHT PAYMENT',
  'FEMA',
  'FIDELITY',
  'FIDUCIARY',
  'FIFTH THIRD',
  'FINANCE',
  'FINANCE AND INSURANCE',
  'FINANCIAL',
  'FINANCIAL ENFORCEMENT',
  'FIRM',
  'first american title',
  'FISCAL SERVICE',
  'FISCAL SERVICES',
  'FLEET',
  'FLORIDA POWER & LIGHT',
  'FORESTRY',
  'FORTIS',
  'foundation',
  'FRANCHISE TAX',
  'FRONTIER COMMUNICATIONS',
  'FUND',
  'FUNDING',
  'FUNDS',
  'FUTURES',
  'G&K SERVICES',
  'GALLAGHER BENEFIT',
  'GAMING COMMISSION',
  'GAS',
  'GAS CO',
  'GAS COMPANY',
  'GE CAPITAL',
  'GE HEALTHCARE FINANCE',
  'GEICO',
  'GENERAL SERVICES',
  'GEORGIA POWER',
  'GM',
  'GM FINANCIAL',
  'GOVERNING BOARD',
  'GOVERNMENT',
  'GOVERNOR',
  'GRACE PERIOD TRUST',
  'GRANT',
  'GREAT PLAINS ENERGY',
  'GREEN DOT BANK',
  'GUARDIAN LIFE',
  'GUSTO',
  'HARBOR',
  'HARTFORD',
  'HEALTH AND HUMAN SERVICES',
  'HEALTH BENEFIT FUND',
  'HEALTH DEPARTMENT',
  'HEALTH INSURANCE',
  'HEALTHSPRING',
  'HIGHMARK',
  'HMRC',
  'HOLDINGS',
  'HOME EQUITY',
  'HOMELAND SECURITY',
  'HONDA',
  'HONDA FINANCE',
  'HOUSING AUTHORITY',
  'HOUSING FINANCE',
  'HUD',
  'HUMANA',
  'HUNTINGTON BANCSHARES',
  'HYDRO',
  'HYUNDAI',
  'IMMIGRATION',
  'IMPORT EXPORT',
  'INDIVIDUAL ACH PAYMENT',
  'INDUSTRIAL DEVELOPMENT',
  'INDUSTRIAL RELATIONS',
  'INSPECTION',
  'INSPECTORATE',
  'INSURANCE',
  'INSURANCE COMMISSION',
  'INSURER',
  'INTELLECTUAL PROPERTY',
  'INTERCOMPANY',
  'INTERNAL REVENUE',
  'internal revenue service',
  'INTERNAL TRANSFER',
  'INTERNATIONAL MONETARY',
  'INVESTMENT',
  'INVESTMENT BOARD',
  'INVESTORS',
  'IRS',
  'ISO',
  'JP',
  'JP MORGAN',
  'JPMORGAN',
  'JUDICIARY',
  'KAISER',
  'KANSAS GAS',
  'KIA',
  'LABOR DEPARTMENT',
  'LAND MANAGEMENT',
  'LASALLE BANK',
  'LEASE',
  'LEASE FINANCING',
  'LEGISLATURE',
  'LENDING',
  'LENDING CLUB',
  'LIBERTY MUTUAL',
  'LINE OF CREDIT',
  'LOAN',
  'LOAN PAYMENT',
  'LOAN SERVICING',
  'LOCKHEED MARTIN FCU',
  'LOTTERY COMMISSION',
  'LPL FINANCIAL',
  'LUMEN TECHNOLOGIES',
  'M&T',
  'MADISON GAS',
  'MAGELLAN HEALTH',
  'MAINE POWER',
  'MANUFACTURERS AND TRADERS',
  'MAPFRE',
  'MARGIN',
  'MARITIME',
  'MARSH',
  'MARSH & MCLENNAN',
  'MAZDA',
  'MB FINANCIAL',
  'MCNA',
  'MDC UTILITIES',
  'MEDICAID',
  'MEDICARE',
  'MEDICARE REIMBURSEMENT',
  'MEDTRONIC FINANCE',
  'MELLON',
  'MEMORIAL HOSPITAL PAYROLL',
  'MERCEDES BENZ FINANCIAL',
  'merrill lynch',
  'MERS',
  'METLIFE',
  'METRO WATER',
  'MILITARY',
  'MILLIMAN BENEFITS',
  'MINING',
  'MINNESOTA POWER',
  'MIZUHO',
  'MORGAN',
  'MORGAN STANLEY',
  'MORTGAGE',
  'MORTGAGE COMPANY',
  'MORTGAGE SERVICING',
  'MOSAIC PAYMENTS',
  'MTA',
  'MUNICIPAL',
  'MUNICIPAL ELECTRIC',
  'MUNICIPAL POWER',
  'MUNICIPALITY',
  'mututal of omaha',
  'NATIONAL BANK',
  'NATIONAL FINANCE',
  'NATIONAL GRID',
  'NATIONAL TREASURY',
  'NAVY',
  'NCR',
  'NEW JERSEY UTILITIES',
  'NISSAN MOTOR ACCEPTANCE',
  'NORTHERN NATURAL GAS',
  'NORTHWESTERN MUTUAL',
  'NSTAR',
  'NUCLEAR',
  'OCCUPATIONAL SAFETY',
  'OCEAN VIEW INSURANCE',
  'OFFICE OF',
  'OFFICE OF MANAGEMENT',
  'OFFICE SUPPLY REIMBURSEMENT',
  'OG&E',
  'OIL',
  'OLD MUTUAL',
  'ONCOR',
  'OPERATIONS',
  'OPTIMUM',
  'PACIFIC GAS & ELECTRIC',
  'PALO ALTO UTILITIES',
  'PARKER HANNIFIN CREDIT',
  'PAYCHEX',
  'PAYCOM',
  'PAYLOCITY',
  'PAYMENTUS',
  'PAYROLL',
  'PAYROLL SERVICE',
  'PENN Y M N C',
  'PENNYMAC',
  'PENSION',
  'PENSION FUND',
  'PEOPLES GAS',
  'PERSHING',
  'petty cash',
  'PG&E',
  'PHARMACY',
  'PHONE COMPANY',
  'PHYSICIANS MUTUAL',
  'PILGRIM',
  'PIMCO',
  'PNC',
  'PORT AUTHORITY',
  'PORT POWER',
  'POSTAL',
  'POWER',
  'POWER AUTHORITY',
  'PPL ELECTRIC',
  'PRA GROUP',
  'PRINCIPAL',
  'PROBATION',
  'PROCURATOR',
  'PROCUREMENT',
  'PROGRESSIVE',
  'PROGRESSIVE ENERGY',
  'PRUDENTIAL',
  'PUBLIC BROADCASTING',
  'PUBLIC HEALTH',
  'PUBLIC SAFETY',
  'PUBLIC SERVICE COMMISSION',
  'PUBLIC SERVICE COMPANY',
  'PUBLIC UTILITIES',
  'PUBLIC UTILITIES COMMISSION',
  'PUBLIC UTILITY',
  'PUBLIC WORKS',
  'PURCHASE CARD PAYMENT',
  'RAILROAD',
  'REAL ESTATE',
  'REAL ESTATE AND RENTAL AND LEASING',
  'RECLAMATION',
  'REDEVELOPMENT',
  'REGENTS',
  'REGIONAL BANK',
  'REGULATORY',
  'reimbursement',
  'RENTAL HOUSING',
  'RENTAL PAYMENT',
  'REPUBLIC SERVICES',
  'RESEARCH GRANT',
  'retirement',
  'REVENUE',
  'REVOLVING FUND',
  'RISK MANAGEMENT',
  'ROAD COMMISSION',
  'ROCKY MOUNTAIN POWER',
  'ROYAL BANK',
  'RSA',
  'SALT RIVER PROJECT',
  'SAVINGS',
  'SAVINGS & LOAN',
  'SCHWAB',
  'SEC',
  'secretary of state',
  'secretary of treasury',
  'SECURITIES',
  'SECURITIES COMMISSION',
  'SECURITY LIFE',
  'SEDGWICK',
  'SETTLEMENT',
  'SEWER AUTHORITY',
  'SHERIFF',
  'SIGNAL MUTUAL',
  'SIXTH DISTRICT',
  'SOCIAL SECURITY',
  'SOLAR',
  'SOUTH CAROLINA ELECTRIC',
  'SOUTHERN CALIFORNIA EDISON',
  'SOUTHERN COMPANY',
  'SOUTHWEST GAS',
  'SPACE AGENCY',
  'SPECTRUM',
  'SPRINT',
  'STANDARDS AGENCY',
  'STATE',
  'STATE BAR',
  'STATE FARM',
  'STATE OF',
  'STATE TAX',
  'STATE TREASURER',
  'STELLANTIS',
  'STREET OPENING PERMIT',
  'SUBSIDY',
  'SUPPLEMENTAL INSURANCE',
  'SUPREME COURT',
  'SYNNOVUS',
  'SYSCO',
  'TARIFF',
  'TAX',
  'tax collector',
  'TAX COMMISSION',
  'TD',
  'TEACHERS RETIREMENT',
  'TELECOM',
  'TELECOMMUNICATIONS',
  'TENNESSEE VALLEY AUTHORITY',
  'THE CAPITAL GROUP',
  'THE COMMONWEALTH',
  'TIAA',
  'TJE COMPENSATION',
  'tmobile',
  't-mobile',
  'T‑MOBILE',
  'Town of',
  'TOWNSHIP',
  'TOYOTA',
  'TOYOTA FINANCIAL',
  'TRADE COMMISSION',
  'TRANSACTION SETTLEMENT',
  'TRANSPORTATION',
  'TRANSPORTATION AUTHORITY',
  'travelers',
  'TREASURER',
  'TREASURY',
  'TRIBAL',
  'TRINET',
  'TRUIST',
  'TRUST',
  'TRUST COMPANY',
  'TRUSTEE',
  'TRUSTEES',
  'TUTOR PERINI PAYROLL',
  'U S DEPARTMENT',
  'U.S. DEPARTMENT',
  'UAW TRUST',
  'UHC',
  'UKG',
  'UNEMPLOYMENT',
  'UNION',
  'UNION GAS',
  'UNITED HEALTH',
  'united healthcare',
  'united state treasury',
  'UNITED STATES',
  'UNIVERSITY',
  'US BANK',
  'us dept of education',
  'us foods',
  'us postal service',
  'USAA',
  'USAA FEDERAL SAVINGS',
  'USDA',
  'usi insurance',
  'UTILITIES',
  'UTILITY BOARD',
  'VA',
  'VANGUARD',
  'VERIZON',
  'VISA',
  'VISTRA',
  'WAGE',
  'WAGES',
  'WALNUT ENERGY',
  'WASTE MANAGEMENT',
  'WATER',
  'WATER AUTHORITY',
  'WATER DISTRICT',
  'WATER FUND',
  'WEC ENERGY',
  'WELFARE',
  'WELLS FARGO',
  'WESTAR ENERGY',
  'WESTERN ALLIANCE BANK',
  'WEX',
  'WIRE',
  'WIRE TRANSFER',
  'WISCONSIN ENERGY',
  'WM SERVICES',
  'WORKERS COMPENSATION',
  'WORKFORCE',
  'WYNDHAM PROFITS',
  'XCEL ENERGY',
  'XFINITY',
  'ZIONS',
  'ZIONS BANK',
  'ZURICH'
];

export interface ExclusionResult {
  isExcluded: boolean;
  matchedKeywords: string[];
  originalName: string;
}

/**
 * Check if a payee name contains any exclusion keywords using comprehensive matching
 */
export function checkKeywordExclusion(
  payeeName: string, 
  exclusionKeywords: string[] = COMPREHENSIVE_EXCLUSION_KEYWORDS
): ExclusionResult {
  if (!payeeName || typeof payeeName !== 'string') {
    return {
      isExcluded: true,
      matchedKeywords: ['invalid-input'],
      originalName: payeeName
    };
  }

  const normalizedName = payeeName.toUpperCase().trim();
  const matchedKeywords: string[] = [];

  // Check each exclusion keyword using case-insensitive partial matching
  for (const keyword of exclusionKeywords) {
    if (!keyword || typeof keyword !== 'string') continue;
    
    const normalizedKeyword = keyword.toUpperCase().trim();
    if (!normalizedKeyword) continue;

    // Use contains matching for better coverage
    if (normalizedName.includes(normalizedKeyword)) {
      matchedKeywords.push(keyword);
    }
  }

  return {
    isExcluded: matchedKeywords.length > 0,
    matchedKeywords,
    originalName: payeeName
  };
}

/**
 * Filter an array of payee names, separating excluded from valid ones
 */
export function filterPayeeNames(
  payeeNames: string[],
  exclusionKeywords: string[] = COMPREHENSIVE_EXCLUSION_KEYWORDS
): {
  validNames: string[];
  excludedNames: Array<{ name: string; reason: string[] }>;
} {
  const validNames: string[] = [];
  const excludedNames: Array<{ name: string; reason: string[] }> = [];

  for (const name of payeeNames) {
    const exclusionResult = checkKeywordExclusion(name, exclusionKeywords);
    
    if (exclusionResult.isExcluded) {
      excludedNames.push({
        name: name,
        reason: exclusionResult.matchedKeywords
      });
    } else {
      validNames.push(name);
    }
  }

  return { validNames, excludedNames };
}

/**
 * Get the comprehensive exclusion keywords
 */
export function getComprehensiveExclusionKeywords(): string[] {
  return [...COMPREHENSIVE_EXCLUSION_KEYWORDS];
}

/**
 * Get the default (basic) exclusion keywords for backward compatibility
 */
export function getDefaultExclusionKeywords(): string[] {
  return [
    'test', 'sample', 'example', 'dummy', 'placeholder', 'temp', 'temporary',
    'unknown', 'na', 'null', 'undefined', 'blank', 'empty', 'void',
    'pending', 'processing', 'error', 'failed', 'invalid', 'debug'
  ];
}

/**
 * Validate exclusion keywords array
 */
export function validateExclusionKeywords(keywords: string[]): string[] {
  if (!Array.isArray(keywords)) {
    console.warn('[EXCLUSION] Invalid keywords array, using comprehensive list');
    return COMPREHENSIVE_EXCLUSION_KEYWORDS;
  }

  return keywords
    .filter(keyword => keyword && typeof keyword === 'string' && keyword.trim())
    .map(keyword => keyword.trim());
}
